/**
 * Mesin AI lokal Bapak Jogja.
 * Modul ini menangani estimasi biaya, itinerary, rating, dan jawaban panduan Yogyakarta.
 * Sistem berjalan sepenuhnya di browser dan menggunakan data dari data.js.
 */
function budgetText(type,days,budget){const b=budgetEstimate(type,days,budget);return `${b.item.label}: ${compactRupiah(b.perMin)}–${compactRupiah(b.perMax)} per orang untuk ${b.duration} hari. Estimasi total ${type} (${b.count} orang) ${compactRupiah(b.groupMin)}–${compactRupiah(b.groupMax)}. Termasuk perkiraan makan, penginapan, transport lokal, dan tiket wisata. Tidak termasuk perjalanan menuju Yogyakarta.`}
function makePlan(type,days,budget){const n=Math.max(1,Math.min(7,Number(days)||2));const item=BUDGET_LEVELS[budget]||BUDGET_LEVELS.sedang;const hotel=item.stay;const pool=[
['Candi Prambanan','Kuliner lokal area timur','Ratu Boko atau kembali ke pusat kota'],['Keraton Yogyakarta dan Taman Sari','Gudeg Wijilan','Malioboro serta Titik Nol pada malam hari'],['Kebun Buah Mangunan','Kuliner Bantul','Pantai Parangtritis saat senja'],['Kaliurang atau museum kawasan Merapi','Warung Kopi Klotok','Kembali melalui koridor utara'],['Kotagede dan sentra perak','Bakmi Jawa atau brongkos','Prawirotaman dan waktu santai'],['Gunungkidul satu zona penuh','Makan siang lokal','Pantai atau gua sesuai cuaca'],['Hari fleksibel','Belanja oleh-oleh','Istirahat sebelum perjalanan pulang']];
let text=`Rencana ${n} hari untuk ${type}\nKategori anggaran: ${budgetText(type,n,budget)}\nGaya menginap: ${hotel}.\n`;
for(let i=0;i<n;i++){const p=pool[i%pool.length];text+=`\nHari ${i+1}\n07.30 Sarapan dan persiapan\n09.00 ${p[0]}\n12.30 ${p[1]}\n15.30 ${p[2]}\n19.00 Kembali ke penginapan atau makan malam\n`}
return text+'\nCatatan: itinerary memakai pengelompokan zona. Periksa jam operasional, cuaca, harga tiket, dan kondisi lalu lintas sebelum berangkat.'}
function allRatingItems(category){if(category==='hotel')return DATA.hotels.map(x=>({...x,category:'Hotel'}));if(category==='kuliner')return DATA.foods.map(x=>({...x,category:'Kuliner'}));if(category==='wisata')return DATA.destinations.map(x=>({...x,category:'Wisata'}));return [...DATA.destinations.map(x=>({...x,category:'Wisata'})),...DATA.hotels.map(x=>({...x,category:'Hotel'})),...DATA.foods.map(x=>({...x,category:'Kuliner'}))]}
function detectCategory(q){if(/hotel|penginapan|resort|villa|vila/.test(q))return 'hotel';if(/kuliner|makan|makanan|restoran|warung|gudeg|sate|kopi/.test(q))return 'kuliner';if(/wisata|destinasi|tempat|candi|pantai|museum|keraton/.test(q))return 'wisata';return 'semua'}
function formatRatingList(items){return items.map((x,i)=>`${i+1}. ${x.name} · ★ ${x.rating} · ${x.location}\n   ${x.description}`).join('\n')}
function ratingAnswer(q){const category=detectCategory(q);let items=allRatingItems(category);const scoreMatch=q.match(/(?:rating|bintang|skor)?\s*(?:minimal|paling sedikit|di atas|lebih dari|sekitar)?\s*([1-5](?:[.,]\d)?)/);const score=scoreMatch?Number(scoreMatch[1].replace(',','.')):null;const isMinimum=/minimal|ke atas|di atas|lebih dari|setidaknya|\+/.test(q);const isLowest=/terendah|paling rendah/.test(q);items.sort((a,b)=>isLowest?a.rating-b.rating:b.rating-a.rating);
if(score!==null){if(/arti|makna|maksud/.test(q))return `Arti skor ★ ${score}: ${RATING_SCALE[Math.max(1,Math.min(5,Math.round(score)))]}\n\nSkor pada website ini adalah skor rekomendasi internal 1–5, bukan rating resmi Google atau platform pemesanan.`;const filtered=isMinimum?items.filter(x=>x.rating>=score):items.filter(x=>Math.abs(x.rating-score)<=.3);if(filtered.length)items=filtered;else return `Belum ada ${category==='semua'?'item':category} dengan skor yang tepat di sekitar ★ ${score} pada basis data lokal. Pilihan terdekat:\n${formatRatingList(items.slice(0,3))}\n\nSkor ini adalah rekomendasi internal dan dapat berbeda dari platform lain.`}
const title=category==='semua'?'wisata, hotel, dan kuliner':category;return `Rating ${title} berdasarkan skor rekomendasi internal 1–5:\n${formatRatingList(items.slice(0,5))}\n\nPanduan: ★1 sangat terbatas, ★2 di bawah rata-rata, ★3 cukup, ★4 baik, ★5 istimewa. Rating bukan data langsung dari Google dan perlu diverifikasi kembali sebelum memesan.`}
function cityGuideAnswer(q){if(/kawasan|area|tinggal di mana|menginap di mana|wilayah/.test(q))return CITY_GUIDE.area;if(/zona|rute|searah|efisien|kelompok/.test(q))return CITY_GUIDE.route;if(/transport|trans jogja|bus|sewa motor|sewa mobil|ojek|grab|gojek/.test(q))return CITY_GUIDE.transport;if(/bandara|yia|stasiun|tugu|lempuyangan|kedatangan/.test(q))return CITY_GUIDE.arrival;if(/budaya|adat|sopan|etika|pakaian|kraton/.test(q))return CITY_GUIDE.culture;if(/sejarah|istimewa|kesultanan|sultan/.test(q))return CITY_GUIDE.history;if(/cuaca|musim|hujan|kemarau/.test(q))return CITY_GUIDE.weather;if(/pantai|ombak|parangtritis|gunungkidul/.test(q))return CITY_GUIDE.beach;if(/merapi|kaliurang|gunung/.test(q))return CITY_GUIDE.merapi;if(/kuliner|makanan|makan|gudeg|sate|bakmi|brongkos/.test(q))return CITY_GUIDE.food;if(/oleh-oleh|souvenir|bakpia|batik|perak/.test(q))return CITY_GUIDE.souvenir;if(/keluarga|anak/.test(q))return CITY_GUIDE.family;if(/pasangan|romantis|honeymoon/.test(q))return CITY_GUIDE.couple;if(/sendiri|solo traveler/.test(q))return CITY_GUIDE.solo;if(/difabel|kursi roda|aksesibilitas|lansia/.test(q))return CITY_GUIDE.accessibility;if(/malam|nightlife|larut/.test(q))return CITY_GUIDE.night;if(/bahasa|jawa|monggo|matur nuwun/.test(q))return CITY_GUIDE.language;if(/foto|fotografi|instagram|drone/.test(q))return CITY_GUIDE.photography;if(/aman|keamanan|darurat|penipuan/.test(q))return CITY_GUIDE.safety;return CITY_GUIDE.overview}
function respond(input){const q=input.toLowerCase().trim();
if(/rating|bintang|skor|tertinggi|terendah|terbaik/.test(q))return ratingAnswer(q);
if(/budget|anggaran|biaya|hemat|sedang|nyaman|premium|berapa juta/.test(q)&&!/itinerary|rencana/.test(q)){const d=(q.match(/([1-7])\s*hari/)||[])[1]||tripDays.value;const b=/premium/.test(q)?'premium':/nyaman/.test(q)?'nyaman':/hemat/.test(q)?'hemat':/sedang/.test(q)?'sedang':tripBudget.value;return budgetText(selectedType,d,b)+'\n\nKategori per hari: Hemat Rp250–400 ribu, Sedang Rp450–700 ribu, Nyaman Rp800 ribu–1,2 juta, Premium Rp1,4–2,2 juta per orang.'}
if(/itinerary|rencana|susun|jadwal|\b[1-7]\s*hari\b/.test(q)){const d=(q.match(/([1-7])\s*hari/)||[])[1]||tripDays.value;const b=/premium/.test(q)?'premium':/nyaman/.test(q)?'nyaman':/hemat/.test(q)?'hemat':/sedang/.test(q)?'sedang':tripBudget.value;return makePlan(selectedType,d,b)}
if(/jogja|yogyakarta|malioboro|kotagede|prawirotaman|bantul|gunungkidul|kaliurang|merapi|pantai|transport|budaya|sejarah|musim|oleh-oleh|bahasa|aman|foto|keluarga|pasangan|solo|difabel|bandara|stasiun/.test(q))return cityGuideAnswer(q);
return 'Saya dapat menjawab lebih mendalam tentang Jogja. Coba tanyakan salah satu contoh berikut:\n• “Hotel dengan rating minimal 4,5”\n• “Kuliner rating tertinggi”\n• “Apa arti rating bintang 4?”\n• “Berapa anggaran hemat 4 hari untuk pasangan?”\n• “Kawasan terbaik untuk menginap pertama kali”\n• “Susun rute pusat kota dan Prambanan”\n• “Tips aman ke pantai selatan”\n\nUntuk cuaca, harga, ketersediaan kamar, dan jam buka real-time, website perlu dihubungkan ke API langsung.'}
